name: test_build
on: 
  push:
    branches:
      - main 
  pull_request: 
    branches:
      - main  
  workflow_dispatch:
    
permissions:
  contents: write 
concurrency: 
  group: ${{github.ref}}
  cancel-in-progress: true 
jobs:
  test: 
    runs-on: ubuntu-latest
    #timeout-minutes: 2 
    steps:
      - name: checkout repo 
        uses:  actions/checkout@v4
        with: 
          fetch-depth: 1
          ref: main 
      - name: Show working directory
        run: pwd

      - name: Show repo tree
        run: ls -R
      - name: setup node 
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: install dependency 
        run: npm ci
      - name: run linting 
        run:  npx eslint .  #linting source code 
      - name: unit test 
        run: npx jest 
      - name: security scan 
        uses: aquasecurity/trivy-action@0.33.1
        with: 
          scan-type: 'fs'
          ignore-unfixed: true 
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: 1 #fail the pipeline if vulnerability are found in the file system
      - name: dependency audit 
        run: npm audit audit-level=high 
      - name: ls file 
        run: ls -la 
